name: Test with Ansible

"on":
  push:
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
  schedule:
    - cron: "12 0 * * *"
  release:
    types:
      - published  # It seems that you can publish directly without creating
      - prereleased
  workflow_dispatch:

env:
  ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/:~/work/
  checkout_path: ansible_collections/devroles/lint_all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: "${{ env.checkout_path }}"
      - name: Update submodules to latest
        run: |
          cd "${{ env.checkout_path }}"
          git submodule update --remote --recursive
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          set -ex
          python -m pip install -U pip
          pip install -U ansible-lint
      - name: Run lint on roles, where it works no matter what
        run: |
          cd "${{ env.checkout_path }}"
          ansible-lint roles/called
          ansible-lint -c tests/ansible-lint.yml roles/called
          ansible-lint roles/caller
          ansible-lint -c tests/ansible-lint.yml roles/caller
      - name: Run lint on playbook, where it works without config specified
        run: |
          cd "${{ env.checkout_path }}"
          ansible-lint playbooks/playbook_caller.yml
      - name: Run lint on playbook, where it fails with config specified
        run: |
          cd "${{ env.checkout_path }}"
          ansible-lint -c tests/ansible-lint.yml playbooks/playbook_caller.yml
